image:
  file: .devcontainer/Dockerfile

tasks:
  - init: bash .devcontainer/onCreateCommand.sh
    command: bash .devcontainer/postStartCommand.sh && bash && exit

vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools-driver-pg
    - mtxr.sqltools

ports:
  - port: 5432
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview
  - port: 39509
    onOpen: open-preview