image:
  file: .devcontainer/Dockerfile

tasks:
  - init: bash .devcontainer/onCreateCommand.sh
    command: bash .devcontainer/postStartCommand.sh && bash && exit

vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools-driver-pg
    - mtxr.sqltools


    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
