# Generated by Django 4.2 on 2023-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('whatTime', models.TimeField()),
                ('repeat', models.BooleanField(default=False)),
                ('whatDate', models.DateField()),
                ('whatDays', models.DateField()),
                ('snooze', models.BooleanField(default=False)),
                ('silent', models.BooleanField(default=False)),
                ('ringtone', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('inGroup', models.BooleanField(default=False)),
                ('group', models.IntegerField()),
                ('isEnabled', models.BooleanField(default=True)),
            ],
        ),
    ]
