# Generated by Django 4.2 on 2023-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0002_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='inGroup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='repeat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='ringtone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='silent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='snooze',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='whatDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='whatDays',
            field=models.DateField(blank=True, null=True),
        ),
    ]
