# Generated by Django 4.2 on 2023-04-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0003_alter_alarm_group_alter_alarm_ingroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='whatDate',
            new_name='alarmDate',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='whatDays',
            new_name='alarmDays',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='group',
            new_name='alarmGroup',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='inGroup',
            new_name='alarmInGroup',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='isEnabled',
            new_name='alarmIsEnabled',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='label',
            new_name='alarmName',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='repeat',
            new_name='alarmRepeat',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='ringtone',
            new_name='alarmRingtone',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='silent',
            new_name='alarmSilent',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='snooze',
            new_name='alarmSnooze',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='whatTime',
            new_name='alarmTime',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='volume',
            new_name='alarmVolume',
        ),
    ]
