# Generated by Django 4.2 on 2023-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0004_rename_whatdate_alarm_alarmdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('repeat', models.BooleanField(default=False)),
                ('whatDate', models.DateField()),
                ('whatDays', models.DateField()),
                ('silent', models.BooleanField(default=False)),
                ('ringtone', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('isEnabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='alarmToGroupBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmId', models.IntegerField()),
                ('alarmGroupId', models.IntegerField()),
            ],
        ),
    ]
