# Generated by Django 4.2 on 2023-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0006_rename_whatdate_alarmgroup_agroupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupDays',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupRepeat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupRingtone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupSilent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alarmgroup',
            name='aGroupVolume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
