# Generated by Django 4.2 on 2023-04-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0007_alter_alarmgroup_agroupdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alarmToGroupBridge',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='alarmInGroup',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarmGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='alarmsquadAPI.alarmgroup'),
        ),
    ]
