# Generated by Django 4.2 on 2023-04-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0008_delete_alarmtogroupbridge_remove_alarm_alarmingroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='alarmsquadAPI.alarmgroup'),
        ),
    ]
