# Generated by Django 4.2 on 2023-04-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0010_ringtone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tGroupName', models.CharField()),
                ('tGroupSilent', models.BooleanField(default=False)),
                ('tGroupRingtone', models.IntegerField()),
                ('tGroupVolume', models.IntegerField()),
                ('tGroupIsEnabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='alarmRingtone',
        ),
        migrations.AddField(
            model_name='alarm',
            name='ringtone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alarmsquadAPI.ringtone'),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerName', models.CharField()),
                ('timerLength', models.TimeField()),
                ('timerSilent', models.BooleanField(default=False)),
                ('timerVolume', models.IntegerField()),
                ('timerInGroup', models.BooleanField(default=False)),
                ('timerIsEnabled', models.BooleanField(default=True)),
                ('ringtone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alarmsquadAPI.ringtone')),
                ('timerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='alarmsquadAPI.timergroup')),
            ],
        ),
    ]
