# Generated by Django 4.2 on 2023-04-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0013_alter_ringtone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='alarmsquadAPI.alarmgroup'),
        ),
    ]
