# Generated by Django 4.2 on 2023-04-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0014_alter_alarm_alarmgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmgroup',
            name='aGroupRingtone',
        ),
        migrations.AddField(
            model_name='alarmgroup',
            name='ringtone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alarmsquadAPI.ringtone'),
        ),
    ]
