# Generated by Django 4.2 on 2023-05-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmsquadAPI', '0015_remove_alarmgroup_agroupringtone_alarmgroup_ringtone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarmGroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='alarmsquadAPI.alarmgroup'),
        ),
    ]
